import { Buildings } from "./Buildings";
import { PopulationClass } from "./PopulationClasses";
import { ResourceNames } from "./Resource";

export const ResourceStrings = {
    PopulationClass: {
        [PopulationClass.Workers]: "Workers",
        [PopulationClass.Operators]: "Operators",
        [PopulationClass.Executives]: "Executives",
        [PopulationClass.Investors]: "Investors",
        [PopulationClass.Synthetics]: "Synthetics",
        [PopulationClass.Protectors]: "Protectors",
        [PopulationClass.Scientists]: "Scientists",
        [PopulationClass.Miners]: "Miners",
        [PopulationClass.Officers]: "Officers",
        [PopulationClass.Ecologists]: "Ecologists",
        [PopulationClass.FieldResearchers]: "Field Researchers",
    },
    Buildings: {
        [Buildings.BiopolymerFactory]: 'Biopolymer Factory',
        [Buildings.RobotAssemblyHall]: 'Robot Assembly Hall',
        [Buildings.PlasmaSmelter]: 'Plasma Smelter',
        [Buildings.CompressionChamber]: 'Compression Chamber',
        [Buildings.IonWelder]: 'Ion Welder',
        [Buildings.RiceFarm]: 'Rice Farm',
        [Buildings.FoodDesignWorkshop]: 'Food Design Workshop',
        [Buildings.DesalinizationPlant]: 'Desalinization Plant',
        [Buildings.VitaminCondensor]: 'Vitamin Condensor',
        [Buildings.BiomedicalLaboratory]: 'Biomedical Laboratory',
        [Buildings.NanoTextileMill]: 'Nano Textile Mill',
        [Buildings.AndroidFactory]: 'Android Factory',
        [Buildings.Cannery]: 'Cannery',
        [Buildings.PharmaLab]: 'Pharma Lab',
        [Buildings.HardwareFabricationPlant]: 'Hardware Fabrication Plant',
        [Buildings.NeuroModuleFactory]: 'Neuro Module Factory',
        [Buildings.ReplicatorFactory]: 'Replicator Factory',
        [Buildings.SpaceGalley]: 'Space Galley',
        [Buildings.CyberneticsFactory]: 'Cybernetics Factory',
        [Buildings.AntiGWorkshop]: 'Anti-G Workshop',
        [Buildings.AlgaeFarm]: 'Algae Farm',
        [Buildings.FeldsparQuarry]: 'Feldspar Quarry',
        [Buildings.Vineyard]: 'Vineyard',
        [Buildings.SoyFarm]: 'Soy Farm',
        [Buildings.DiamondMine]: 'Diamond Mine',
        [Buildings.FlaxPlantation]: 'Flax Plantation',
        [Buildings.SiliconMine]: 'Silicon Mine',
        [Buildings.FruitPlantation]: 'Fruit Plantation',
        [Buildings.CobaltMine]: 'Cobalt Mine',
        [Buildings.SunflowerFarm]: 'Sunflower Farm',
        [Buildings.MolybdenumMine]: 'Molybdenum Mine',
        [Buildings.AluminiumMine]: 'Aluminium Mine',
        [Buildings.DeepWaterCoralFarm]: 'Deep Water Coral Farm',
        [Buildings.FishingHarbor]: 'Fishing Harbor',
        [Buildings.MethaneExtractor]: 'Methane Extractor',
        [Buildings.CoreIceDriller]: 'Core Ice Driller',
        [Buildings.TitaniumMine]: 'Titanium Mine',
        [Buildings.Helium3Extractor]: 'Helium-3 Extractor',
        [Buildings.KREEPGatherer]: 'KREEP Gatherer',
        [Buildings.AeroponicFarm]: 'Aeroponic Farm',
        [Buildings.MicrofabricationHall]: 'Microfabrication Hall',
        [Buildings.SynthcellIncubator]: 'Synthcell Incubator',
        [Buildings.CattleRanch]: 'Cattle Ranch',
        [Buildings.SynapticCircuitPlant]: 'Synaptic Circuit Plant',
        [Buildings.NanoCuttingUnit]: 'Nano Cutting Unit',
        [Buildings.QubitFactory]: 'Qubit Factory',
        [Buildings.CryogenicsLab]: 'Cryogenics Lab',
        [Buildings.DeuteriumExtractor]: 'Deuterium Extractor',
        [Buildings.OxygenSeperator]: 'Oxygen Seperator',
        [Buildings.FusionCellPlant]: 'Fusion Cell Plant',
        [Buildings.GrapheneFactory]: 'Graphene Factory',
        [Buildings.IridiumMine]: 'Iridium Mine',
        [Buildings.MagnetiteMine]: 'Magnetite Mine',
        [Buildings.PetrochemicalRefinery]: 'Petrochemical Refinery',
        [Buildings.SmartDroneFactory]: 'Smart Drone Factory',
        [Buildings.AllWeatherParkaStore]: 'All-Weather Parka Store',
        [Buildings.MedibotFactory]: 'Medibot Factory',
    },
    ResourceNames: {
        [ResourceNames.Biopolymers]: 'Biopolymers',
        [ResourceNames.ConstructOBots]: 'Construct-O-Bots',
        [ResourceNames.SuperAlloys]: 'Super Alloys',
        [ResourceNames.MetalFoam]: 'Metal Foam',
        [ResourceNames.TitaniumPlating]: 'Titanium Plating',
        [ResourceNames.OrganicFood]: 'Organic Food',
        [ResourceNames.LuxuryFood]: 'Luxury Food',
        [ResourceNames.Water]: 'Water',
        [ResourceNames.VitaDrinks]: 'Vita Drinks',
        [ResourceNames.Rejuvenators]: 'Rejuvenators',
        [ResourceNames.IntelliWear]: 'IntelliWear',
        [ResourceNames.Androids]: 'Androids',
        [ResourceNames.CannedFood]: 'Canned Food',
        [ResourceNames.Stimulants]: 'Stimulants',
        [ResourceNames.QuantumComputers]: 'Quantum Computers',
        [ResourceNames.NeruoImplants]: 'Neruo Implants',
        [ResourceNames.Replicators]: 'Replicators',
        [ResourceNames.LunarLunch]: 'Lunar Lunch',
        [ResourceNames.Bioenhancers]: 'Bioenhancers',
        [ResourceNames.AntiGravCompensators]: 'Anti-Grav Compensators',
        [ResourceNames.Algae]: 'Algae',
        [ResourceNames.NanoCeramics]: 'Nano Ceramics',
        [ResourceNames.Wine]: 'Wine',
        [ResourceNames.SoyBeans]: 'Soy Beans',
        [ResourceNames.Diamonds]: 'Diamonds',
        [ResourceNames.FlaxFibers]: 'Flax Fibers',
        [ResourceNames.Silicon]: 'Silicon',
        [ResourceNames.Fruit]: 'Fruit',
        [ResourceNames.Cobalt]: 'Cobalt',
        [ResourceNames.Bioresin]: 'Bioresin',
        [ResourceNames.Molybdenum]: 'Molybdenum',
        [ResourceNames.Aluminium]: 'Aluminium',
        [ResourceNames.DeepWaterCorals]: 'Deep Water Corals',
        [ResourceNames.Fish]: 'Fish',
        [ResourceNames.MethaneIce]: 'Methane Ice',
        [ResourceNames.MoonIce]: 'Moon Ice',
        [ResourceNames.Titanium]: 'Titanium',
        [ResourceNames.Helium3]: 'Helium-3',
        [ResourceNames.RareEarthElements]: 'Rare Earth Elements',
        [ResourceNames.MoonCrops]: 'Moon Crops',
        [ResourceNames.Microchips]: 'Microchips',
        [ResourceNames.SynthCells]: 'Synth Cells',
        [ResourceNames.Beef]: 'Beef',
        [ResourceNames.SynapticCircuits]: 'Synaptic Circuits',
        [ResourceNames.MultispecPrisms]: 'Multispec Prisms',
        [ResourceNames.QubitProcessors]: 'Qubit Processors',
        [ResourceNames.SuperCoolants]: 'Super Coolants',
        [ResourceNames.Deuterium]: 'Deuterium',
        [ResourceNames.Oxygen]: 'Oxygen',
        [ResourceNames.FusionCells]: 'Fusion Cells',
        [ResourceNames.Graphene]: 'Graphene',
        [ResourceNames.Iridium]: 'Iridium',
        [ResourceNames.Magnetite]: 'Magnetite',
        [ResourceNames.Petrochemicals]: 'Petrochemicals',
        [ResourceNames.SmartDrones]: 'Smart Drones',
        [ResourceNames.AllWeatherParkas]: 'All-Weather Parkas',
        [ResourceNames.Medibots]: 'Medibots',
    },
};