const Environments = {
    Temperate: 'Temperate',
    Arctic: 'Arctic',
    Lunar: 'Lunar',
    Tundra: 'Tundra',
};

const PopulationClasses = {
    Workers: 'Workers',
    Operators: 'Operators',
    Executives: 'Executives',
    Investors: 'Investors',
    Synthetics: 'Synthetics',
    Protectors: 'Protectors',
    Scientists: 'Scientists',
    Miners: 'Miners',
    Officers: 'Officers',
    Ecologists: 'Ecologists',
    FieldResearchers: 'FieldResearchers',
};

const PopulationClassesByEnvironment = {
    [Environments.Temperate]: [
        PopulationClasses.Workers,
        PopulationClasses.Operators,
        PopulationClasses.Executives,
        PopulationClasses.Investors,
        PopulationClasses.Synthetics,
    ],
    [Environments.Arctic]: [
        PopulationClasses.Protectors,
        PopulationClasses.Scientists,
    ],
    [Environments.Lunar]: [
        PopulationClasses.Miners,
        PopulationClasses.Officers,
    ],
    [Environments.Tundra]: [
        PopulationClasses.Ecologists,
        PopulationClasses.FieldResearchers,
    ],
};

const Needs = {
    Food: 'Food',
    Drink: 'Drink',
    Lifestyle: 'Lifestyle',
    Property: 'Property',
    Oxygen: 'Oxygen',
    HealthCare: 'HealthCare',
};

const Resources = {
    Biopolymers: 'Biopolymers',
    ConstructOBots: 'ConstructOBots',
    SuperAlloys: 'SuperAlloys',
    MetalFoam: 'MetalFoam',
    TitaniumPlating: 'TitaniumPlating',
    OrganicFood: 'OrganicFood',
    LuxuryFood: 'LuxuryFood',
    Water: 'Water',
    VitaDrinks: 'VitaDrinks',
    Rejuvenators: 'Rejuvenators',
    IntelliWear: 'IntelliWear',
    Androids: 'Androids',
    CannedFood: 'CannedFood',
    Stimulants: 'Stimulants',
    QuantumComputers: 'QuantumComputers',
    NeruoImplants: 'NeruoImplants',
    Replicators: 'Replicators',
    LunarLunch: 'LunarLunch',
    Bioenhancers: 'Bioenhancers',
    AntiGravCompensators: 'AntiGravCompensators',
    Algae: 'Algae',
    NanoCeramics: 'NanoCeramics',
    Wine: 'Wine',
    SoyBeans: 'SoyBeans',
    Diamonds: 'Diamonds',
    FlaxFibers: 'FlaxFibers',
    Silicon: 'Silicon',
    Fruit: 'Fruit',
    Cobalt: 'Cobalt',
    Bioresin: 'Bioresin',
    Molybdenum: 'Molybdenum',
    Aluminium: 'Aluminium',
    DeepWaterCorals: 'DeepWaterCorals',
    Fish: 'Fish',
    MethaneIce: 'MethaneIce',
    MoonIce: 'MoonIce',
    Titanium: 'Titanium',
    Helium3: 'Helium3',
    RareEarthElements: 'RareEarthElements',
    MoonCrops: 'MoonCrops',
    Microchips: 'Microchips',
    SynthCells: 'SynthCells',
    Beef: 'Beef',
    SynapticCircuits: 'SynapticCircuits',
    MultispecPrisms: 'MultispecPrisms',
    QubitProcessors: 'QubitProcessors',
    SuperCoolants: 'SuperCoolants',
    Deuterium: 'Deuterium',
    Oxygen: 'Oxygen',
    FusionCells: 'FusionCells',
    Graphene: 'Graphene',
    Iridium: 'Iridium',
    Magnetite: 'Magnetite',
    Petrochemicals: 'Petrochemicals',
};

const Buildings = {
    BiopolymerFactory: 'BiopolymerFactory',
    RobotAssemblyHall: 'RobotAssemblyHall',
    PlasmaSmelter: 'PlasmaSmelter',
    CompressionChamber: 'CompressionChamber',
    IonWelder: 'IonWelder',
    RiceFarm: 'RiceFarm',
    FoodDesignWorkshop: 'FoodDesignWorkshop',
    DesalinizationPlant: 'DesalinizationPlant',
    VitaminCondensor: 'VitaminCondensor',
    BiomedicalLaboratory: 'BiomedicalLaboratory',
    NanoTextileMill: 'NanoTextileMill',
    AndroidFactory: 'AndroidFactory',
    Cannery: 'Cannery',
    PharmaLab: 'PharmaLab',
    HardwareFabricationPlant: 'HardwareFabricationPlant',
    NeuroModuleFactory: 'NeuroModuleFactory',
    ReplicatorFactory: 'ReplicatorFactory',
    SpaceGalley: 'SpaceGalley',
    CyberneticsFactory: 'CyberneticsFactory',
    AntiGWorkshop: 'AntiGWorkshop',
    AlgaeFarm: 'AlgaeFarm',
    FeldsparQuarry: 'FeldsparQuarry',
    Vineyard: 'Vineyard',
    SoyFarm: 'SoyFarm',
    DiamondMine: 'DiamondMine',
    FlaxPlantation: 'FlaxPlantation',
    SiliconMine: 'SiliconMine',
    FruitPlantation: 'FruitPlantation',
    CobaltMine: 'CobaltMine',
    SunflowerFarm: 'SunflowerFarm',
    MolybdenumMine: 'MolybdenumMine',
    AluminiumMine: 'AluminiumMine',
    DeepWaterCoralFarm: 'DeepWaterCoralFarm',
    FishingHarbor: 'FishingHarbor',
    MethaneExtractor: 'MethaneExtractor',
    CoreIceDriller: 'CoreIceDriller',
    TitaniumMine: 'TitaniumMine',
    Helium3Extractor: 'Helium3Extractor',
    KREEPGatherer: 'KREEPGatherer',
    AeroponicFarm: 'AeroponicFarm',
    MicrofabricationHall: 'MicrofabricationHall',
    SynthcellIncubator: 'SynthcellIncubator',
    CattleRanch: 'CattleRanch',
    SynapticCircuitPlant: 'SynapticCircuitPlant',
    NanoCuttingUnit: 'NanoCuttingUnit',
    QubitFactory: 'QubitFactory',
    CryogenicsLab: 'CryogenicsLab',
    DeuteriumExtractor: 'DeuteriumExtractor',
    OxygenSeperator: 'OxygenSeperator',
    FusionCellPlant: 'FusionCellPlant',
    GrapheneFactory: 'GrapheneFactory',
    IridiumMine: 'IridiumMine',
    MagnetiteMine: 'MagnetiteMine',
    PetrochemicalRefinery: 'PetrochemicalRefinery',
};

const BuildingsByResource = {
    [Resources.Biopolymers]: Buildings.BiopolymerFactory,
    [Resources.ConstructOBots]: Buildings.RobotAssemblyHall,
    [Resources.SuperAlloys]: Buildings.PlasmaSmelter,
    [Resources.MetalFoam]: Buildings.CompressionChamber,
    [Resources.TitaniumPlating]: Buildings.IonWelder,
    [Resources.OrganicFood]: Buildings.RiceFarm,
    [Resources.LuxuryFood]: Buildings.FoodDesignWorkshop,
    [Resources.Water]: Buildings.DesalinizationPlant,
    [Resources.VitaDrinks]: Buildings.VitaminCondensor,
    [Resources.Rejuvenators]: Buildings.BiomedicalLaboratory,
    [Resources.IntelliWear]: Buildings.NanoTextileMill,
    [Resources.Androids]: Buildings.AndroidFactory,
    [Resources.CannedFood]: Buildings.Cannery,
    [Resources.Stimulants]: Buildings.PharmaLab,
    [Resources.QuantumComputers]: Buildings.HardwareFabricationPlant,
    [Resources.NeruoImplants]: Buildings.NeuroModuleFactory,
    [Resources.Replicators]: Buildings.ReplicatorFactory,
    [Resources.LunarLunch]: Buildings.SpaceGalley,
    [Resources.Bioenhancers]: Buildings.CyberneticsFactory,
    [Resources.AntiGravCompensators]: Buildings.AntiGWorkshop,
    [Resources.Algae]: Buildings.AlgaeFarm,
    [Resources.NanoCeramics]: Buildings.FeldsparQuarry,
    [Resources.Wine]: Buildings.Vineyard,
    [Resources.SoyBeans]: Buildings.SoyFarm,
    [Resources.Diamonds]: Buildings.DiamondMine,
    [Resources.FlaxFibers]: Buildings.FlaxPlantation,
    [Resources.Silicon]: Buildings.SiliconMine,
    [Resources.Fruit]: Buildings.FruitPlantation,
    [Resources.Cobalt]: Buildings.CobaltMine,
    [Resources.Bioresin]: Buildings.SunflowerFarm,
    [Resources.Molybdenum]: Buildings.MolybdenumMine,
    [Resources.Aluminium]: Buildings.AluminiumMine,
    [Resources.DeepWaterCorals]: Buildings.DeepWaterCoralFarm,
    [Resources.Fish]: Buildings.FishingHarbor,
    [Resources.MethaneIce]: Buildings.MethaneExtractor,
    [Resources.MoonIce]: Buildings.CoreIceDriller,
    [Resources.Titanium]: Buildings.TitaniumMine,
    [Resources.Helium3]: Buildings.Helium3Extractor,
    [Resources.RareEarthElements]: Buildings.KREEPGatherer,
    [Resources.MoonCrops]: Buildings.AeroponicFarm,
    [Resources.Microchips]: Buildings.MicrofabricationHall,
    [Resources.SynthCells]: Buildings.SynthcellIncubator,
    [Resources.Beef]: Buildings.CattleRanch,
    [Resources.SynapticCircuits]: Buildings.SynapticCircuitPlant,
    [Resources.MultispecPrisms]: Buildings.NanoCuttingUnit,
    [Resources.QubitProcessors]: Buildings.QubitFactory,
    [Resources.SuperCoolants]: Buildings.CryogenicsLab,
    [Resources.Deuterium]: Buildings.DeuteriumExtractor,
    [Resources.Oxygen]: Buildings.OxygenSeperator,
    [Resources.FusionCells]: Buildings.FusionCellPlant,
    [Resources.Graphene]: Buildings.GrapheneFactory,
    [Resources.Iridium]: Buildings.IridiumMine,
    [Resources.Magnetite]: Buildings.MagnetiteMine,
    [Resources.Petrochemicals]: Buildings.PetrochemicalRefinery,
};

const LocalizedStrings = {
    [Environments.Temperate]: 'Temperate',
    [Environments.Arctic]: 'Arctic',
    [Environments.Lunar]: 'Lunar',
    [Environments.Tundra]: 'Tundra',
    [PopulationClasses.Workers]: 'Workers',
    [PopulationClasses.Operators]: 'Operators',
    [PopulationClasses.Executives]: 'Executives',
    [PopulationClasses.Investors]: 'Investors',
    [PopulationClasses.Synthetics]: 'Synthetics',
    [PopulationClasses.Protectors]: 'Protectors',
    [PopulationClasses.Scientists]: 'Scientists',
    [PopulationClasses.Miners]: 'Miners',
    [PopulationClasses.Officers]: 'Officers',
    [PopulationClasses.Ecologists]: 'Ecologists',
    [PopulationClasses.FieldResearchers]: 'Field Researchers',
    [Needs.Food]: 'Food',
    [Needs.Drink]: 'Drink',
    [Needs.Lifestyle]: 'Lifestyle',
    [Needs.Property]: 'Property',
    [Needs.Oxygen]: 'Oxygen',
    [Needs.HealthCare]: 'Health Care',
    [Resources.Biopolymers]: 'Biopolymers',
    [Resources.ConstructOBots]: 'Construct-O-Bots',
    [Resources.SuperAlloys]: 'Super Alloys',
    [Resources.MetalFoam]: 'Metal Foam',
    [Resources.TitaniumPlating]: 'Titanium Plating',
    [Resources.OrganicFood]: 'Organic Food',
    [Resources.LuxuryFood]: 'Luxury Food',
    [Resources.Water]: 'Water',
    [Resources.VitaDrinks]: 'Vita Drinks',
    [Resources.Rejuvenators]: 'Rejuvenators',
    [Resources.IntelliWear]: 'IntelliWear',
    [Resources.Androids]: 'Androids',
    [Resources.CannedFood]: 'Canned Food',
    [Resources.Stimulants]: 'Stimulants',
    [Resources.QuantumComputers]: 'Quantum Computers',
    [Resources.NeruoImplants]: 'Neruo Implants',
    [Resources.Replicators]: 'Replicators',
    [Resources.LunarLunch]: 'Lunar Lunch',
    [Resources.Bioenhancers]: 'Bioenhancers',
    [Resources.AntiGravCompensators]: 'Anti-Grav Compensators',
    [Resources.Algae]: 'Algae',
    [Resources.NanoCeramics]: 'Nano Ceramics',
    [Resources.Wine]: 'Wine',
    [Resources.SoyBeans]: 'Soy Beans',
    [Resources.Diamonds]: 'Diamonds',
    [Resources.FlaxFibers]: 'Flax Fibers',
    [Resources.Silicon]: 'Silicon',
    [Resources.Fruit]: 'Fruit',
    [Resources.Cobalt]: 'Cobalt',
    [Resources.Bioresin]: 'Bioresin',
    [Resources.Molybdenum]: 'Molybdenum',
    [Resources.Aluminium]: 'Aluminium',
    [Resources.DeepWaterCorals]: 'Deep Water Corals',
    [Resources.Fish]: 'Fish',
    [Resources.MethaneIce]: 'Methane Ice',
    [Resources.MoonIce]: 'Moon Ice',
    [Resources.Titanium]: 'Titanium',
    [Resources.Helium3]: 'Helium-3',
    [Resources.RareEarthElements]: 'Rare Earth Elements',
    [Resources.MoonCrops]: 'Moon Crops',
    [Resources.Microchips]: 'Microchips',
    [Resources.SynthCells]: 'Synth Cells',
    [Resources.Beef]: 'Beef',
    [Resources.SynapticCircuits]: 'Synaptic Circuits',
    [Resources.MultispecPrisms]: 'Multispec Prisms',
    [Resources.QubitProcessors]: 'Qubit Processors',
    [Resources.SuperCoolants]: 'Super Coolants',
    [Resources.Deuterium]: 'Deuterium',
    [Resources.Oxygen]: 'Oxygen',
    [Resources.FusionCells]: 'Fusion Cells',
    [Resources.Graphene]: 'Graphene',
    [Resources.Iridium]: 'Iridium',
    [Resources.Magnetite]: 'Magnetite',
    [Resources.Petrochemicals]: 'Petrochemicals',
    [Buildings.BiopolymerFactory]: 'Biopolymer Factory',
    [Buildings.RobotAssemblyHall]: 'Robot Assembly Hall',
    [Buildings.PlasmaSmelter]: 'Plasma Smelter',
    [Buildings.CompressionChamber]: 'Compression Chamber',
    [Buildings.IonWelder]: 'Ion Welder',
    [Buildings.RiceFarm]: 'Rice Farm',
    [Buildings.FoodDesignWorkshop]: 'Food Design Workshop',
    [Buildings.DesalinizationPlant]: 'Desalinization Plant',
    [Buildings.VitaminCondensor]: 'Vitamin Condensor',
    [Buildings.BiomedicalLaboratory]: 'Biomedical Laboratory',
    [Buildings.NanoTextileMill]: 'Nano Textile Mill',
    [Buildings.AndroidFactory]: 'Android Factory',
    [Buildings.Cannery]: 'Cannery',
    [Buildings.PharmaLab]: 'Pharma Lab',
    [Buildings.HardwareFabricationPlant]: 'Hardware Fabrication Plant',
    [Buildings.NeuroModuleFactory]: 'Neuro Module Factory',
    [Buildings.ReplicatorFactory]: 'Replicator Factory',
    [Buildings.SpaceGalley]: 'Space Galley',
    [Buildings.CyberneticsFactory]: 'Cybernetics Factory',
    [Buildings.AntiGWorkshop]: 'Anti-G Workshop',
    [Buildings.AlgaeFarm]: 'Algae Farm',
    [Buildings.FeldsparQuarry]: 'Feldspar Quarry',
    [Buildings.Vineyard]: 'Vineyard',
    [Buildings.SoyFarm]: 'Soy Farm',
    [Buildings.DiamondMine]: 'Diamond Mine',
    [Buildings.FlaxPlantation]: 'Flax Plantation',
    [Buildings.SiliconMine]: 'Silicon Mine',
    [Buildings.FruitPlantation]: 'Fruit Plantation',
    [Buildings.CobaltMine]: 'Cobalt Mine',
    [Buildings.SunflowerFarm]: 'Sunflower Farm',
    [Buildings.MolybdenumMine]: 'Molybdenum Mine',
    [Buildings.AluminiumMine]: 'Aluminium Mine',
    [Buildings.DeepWaterCoralFarm]: 'Deep Water Coral Farm',
    [Buildings.FishingHarbor]: 'Fishing Harbor',
    [Buildings.MethaneExtractor]: 'Methane Extractor',
    [Buildings.CoreIceDriller]: 'Core Ice Driller',
    [Buildings.TitaniumMine]: 'Titanium Mine',
    [Buildings.Helium3Extractor]: 'Helium-3 Extractor',
    [Buildings.KREEPGatherer]: 'KREEP Gatherer',
    [Buildings.AeroponicFarm]: 'Aeroponic Farm',
    [Buildings.MicrofabricationHall]: 'Microfabrication Hall',
    [Buildings.SynthcellIncubator]: 'Synthcell Incubator',
    [Buildings.CattleRanch]: 'Cattle Ranch',
    [Buildings.SynapticCircuitPlant]: 'Synaptic Circuit Plant',
    [Buildings.NanoCuttingUnit]: 'Nano Cutting Unit',
    [Buildings.QubitFactory]: 'Qubit Factory',
    [Buildings.CryogenicsLab]: 'Cryogenics Lab',
    [Buildings.DeuteriumExtractor]: 'Deuterium Extractor',
    [Buildings.OxygenSeperator]: 'Oxygen Seperator',
    [Buildings.FusionCellPlant]: 'Fusion Cell Plant',
    [Buildings.GrapheneFactory]: 'Graphene Factory',
    [Buildings.IridiumMine]: 'Iridium Mine',
    [Buildings.MagnetiteMine]: 'Magnetite Mine',
    [Buildings.PetrochemicalRefinery]: 'Petrochemical Refinery',
};

export {Environments, PopulationClasses, PopulationClassesByEnvironment, Needs, Resources, Buildings, BuildingsByResource, LocalizedStrings}